#-------------------------------
# General Site Settings

menu:
- {name: 'Art', url: ''}
- {name: 'Blog',     url: 'blog'}
- {name: 'Gallery',  url: 'gallery'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Piece #0',  url: 'proj-0'}
- {name: 'Piece #1',  url: 'proj-1'}
- {name: 'Piece #2',  url: 'proj-2'}
- {name: 'Piece #3',  url: 'proj-3'}
- {name: 'Piece #4',  url: 'proj-4'}
- {name: 'Piece #5',  url: 'proj-5'}
- {name: 'Piece #6',  url: 'proj-6'}
- {name: 'Piece #7',  url: 'proj-7'}
- {name: 'Piece #8',  url: 'proj-8'}
- {name: 'Piece #9',  url: 'proj-9'}
- {name: 'Piece #10',  url: 'proj-10'}
- {name: 'Piece #11',  url: 'proj-11'}
- {name: 'Piece #12',  url: 'proj-12'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://instagram.com/kaktuspijani'}
- {icon: 'envelope',  link: 'mailto:mailto:kaktuspijani@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
